use anyhow::{bail, Context, Result};
use std::path::Path;

// ── Public types ──────────────────────────────────────────────────────────────

/// A single fund holding from any brokerage account.
#[derive(Debug, Clone)]
pub struct RawHolding {
    /// Human-readable account name (from config).
    pub account_name: String,
    /// Fund name or ticker exactly as it appears in the source file.
    /// Used to look up the asset category in [fund_categories].
    pub fund_name: String,
    /// Current market value in dollars.
    pub value: f64,
}

#[derive(Debug, Clone, Copy)]
pub enum BrokerageFormat {
    /// Vanguard "My Account" positions CSV.
    /// Key columns: Symbol (ticker), Total Value
    /// The parser tries Symbol first; falls back to Description.
    Vanguard,

    /// Empower positions CSV generated by scripts/empower_pdf_to_csv.py.
    /// Key columns: Fund Name, Ending Balance
    Empower,

    /// Alight / Ford SSIP quarterly CSV export.
    /// Key columns: Fund Name, Closing Balance
    Alight,
}

impl BrokerageFormat {
    pub fn from_str(s: &str) -> Result<Self> {
        match s.to_lowercase().as_str() {
            "vanguard" => Ok(Self::Vanguard),
            "empower"  => Ok(Self::Empower),
            "alight"   => Ok(Self::Alight),
            other => bail!(
                "Unknown brokerage format '{}'. Valid values: vanguard, empower, alight",
                other
            ),
        }
    }
}

// ── Main entry point ──────────────────────────────────────────────────────────

/// Parse a brokerage CSV file and return a list of non-zero holdings.
///
/// Unmapped funds are the caller's concern — this function returns whatever is
/// in the file; category resolution happens in portfolio.rs.
///
/// Funds with a zero or negative balance are silently skipped.
pub fn parse_csv(
    path: &Path,
    format: BrokerageFormat,
    account_name: &str,
) -> Result<Vec<RawHolding>> {
    match format {
        BrokerageFormat::Vanguard => parse_vanguard(path, account_name),
        BrokerageFormat::Empower  => parse_empower(path, account_name),
        BrokerageFormat::Alight   => parse_alight(path, account_name),
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Strip dollar signs, commas, and surrounding whitespace, then parse as f64.
fn parse_dollars(raw: &str) -> Result<f64> {
    let cleaned = raw.trim().replace('$', "").replace(',', "");
    cleaned
        .parse::<f64>()
        .with_context(|| format!("could not parse '{}' as a dollar amount", raw))
}

/// Normalise whitespace in a string: trim ends and collapse internal runs
/// of spaces/tabs to a single space.  This is used for fund name lookup.
pub fn normalise(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

// ── Vanguard ──────────────────────────────────────────────────────────────────
//
// Vanguard "My Accounts > Holdings" CSV export.
// Header row (may be preceded by account summary lines Vanguard prepends):
//   Account Number,Account Name,Symbol,Description,Shares,Share Price,Total Value,
// We search for the header by looking for a row that contains both "Symbol"
// and "Total Value" as column names, making the parser robust to Vanguard's
// habit of prepending a few lines of account summary before the real CSV.

fn parse_vanguard(path: &Path, account_name: &str) -> Result<Vec<RawHolding>> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("could not read {}", path.display()))?;

    let mut rdr = csv::ReaderBuilder::new()
        .flexible(true)
        .from_reader(content.as_bytes());

    // Find column indices by scanning for the header row.
    let headers = rdr.headers()
        .with_context(|| format!("no header row in {}", path.display()))?;

    let symbol_col = find_col(headers, "Symbol");
    // Vanguard uses "Investment Name"; older exports used "Description"
    let desc_col   = find_col(headers, "Investment Name")
        .or_else(|| find_col(headers, "Description"));
    let value_col  = find_col(headers, "Total Value")
        .with_context(|| {
            format!(
                "Vanguard CSV '{}' is missing a 'Total Value' column.\n\
                 Columns found: {}",
                path.display(),
                headers.iter().collect::<Vec<_>>().join(", ")
            )
        })?;

    let mut holdings = Vec::new();

    for (row_num, result) in rdr.records().enumerate() {
        let record = result.with_context(|| {
            format!("parse error on row {} of {}", row_num + 2, path.display())
        })?;

        let raw_value = match record.get(value_col) {
            Some(v) => v,
            None => continue,
        };
        let value = match parse_dollars(raw_value) {
            Ok(v) if v > 0.0 => v,
            _ => continue,
        };

        // Prefer ticker symbol; fall back to description.
        let fund_name = match (symbol_col, desc_col) {
            (Some(sc), _) if !record.get(sc).unwrap_or("").trim().is_empty() => {
                normalise(record.get(sc).unwrap_or(""))
            }
            (_, Some(dc)) => normalise(record.get(dc).unwrap_or("")),
            _ => continue,
        };
        if fund_name.is_empty() {
            continue;
        }

        holdings.push(RawHolding {
            account_name: account_name.to_string(),
            fund_name,
            value,
        });
    }

    if holdings.is_empty() {
        bail!(
            "No holdings found in Vanguard CSV '{}'. \
             Check the file is a positions export (not a transaction history).",
            path.display()
        );
    }

    Ok(holdings)
}

// ── Empower (generated CSV) ───────────────────────────────────────────────────
//
// Generated by scripts/empower_pdf_to_csv.py from the quarterly PDF statement.
// Header: Fund Name, Ending Balance
//
// Example:
//   Fund Name,Ending Balance
//   Fidelity 500 Index,5000.00

fn parse_empower(path: &Path, account_name: &str) -> Result<Vec<RawHolding>> {
    let mut rdr = csv::ReaderBuilder::new()
        .flexible(true)
        .from_path(path)
        .with_context(|| format!("could not open {}", path.display()))?;

    let headers = rdr.headers()
        .with_context(|| format!("no header row in {}", path.display()))?;

    let name_col = find_col(headers, "Fund Name")
        .with_context(|| {
            format!(
                "Empower CSV '{}' is missing a 'Fund Name' column.\n\
                 Did you generate it with scripts/empower_pdf_to_csv.py?\n\
                 Columns found: {}",
                path.display(),
                headers.iter().collect::<Vec<_>>().join(", ")
            )
        })?;

    let value_col = find_col(headers, "Ending Balance")
        .with_context(|| {
            format!(
                "Empower CSV '{}' is missing an 'Ending Balance' column.\n\
                 Columns found: {}",
                path.display(),
                headers.iter().collect::<Vec<_>>().join(", ")
            )
        })?;

    let mut holdings = Vec::new();

    for (row_num, result) in rdr.records().enumerate() {
        let record = result.with_context(|| {
            format!("parse error on row {} of {}", row_num + 2, path.display())
        })?;

        let fund_name = normalise(record.get(name_col).unwrap_or(""));
        if fund_name.is_empty() {
            continue;
        }

        let value = match parse_dollars(record.get(value_col).unwrap_or("")) {
            Ok(v) if v > 0.0 => v,
            _ => continue,
        };

        holdings.push(RawHolding {
            account_name: account_name.to_string(),
            fund_name,
            value,
        });
    }

    if holdings.is_empty() {
        bail!(
            "No holdings found in Empower CSV '{}'. \
             Re-run scripts/empower_pdf_to_csv.py on your latest statement.",
            path.display()
        );
    }

    Ok(holdings)
}

// ── Alight / Ford SSIP ────────────────────────────────────────────────────────
//
// Quarterly CSV export from the SSIP portal (Alight Solutions).
//
// Header (quoted):
//   "Plan","Category","Asset Class","Fund Name","Current Mix","Future Investments",
//   "Date Range","Opening Balance","Gains/Losses","Other Activity",
//   "Closing Balance","Units","Fund Price","Fund Return"
//
// We use "Fund Name" and "Closing Balance".

fn parse_alight(path: &Path, account_name: &str) -> Result<Vec<RawHolding>> {
    let mut rdr = csv::ReaderBuilder::new()
        .flexible(true)
        .from_path(path)
        .with_context(|| format!("could not open {}", path.display()))?;

    let headers = rdr.headers()
        .with_context(|| format!("no header row in {}", path.display()))?;

    let name_col = find_col(headers, "Fund Name")
        .with_context(|| {
            format!(
                "Alight CSV '{}' is missing a 'Fund Name' column.\n\
                 Columns found: {}",
                path.display(),
                headers.iter().collect::<Vec<_>>().join(", ")
            )
        })?;

    let value_col = find_col(headers, "Closing Balance")
        .with_context(|| {
            format!(
                "Alight CSV '{}' is missing a 'Closing Balance' column.\n\
                 Columns found: {}",
                path.display(),
                headers.iter().collect::<Vec<_>>().join(", ")
            )
        })?;

    let mut holdings = Vec::new();

    for (row_num, result) in rdr.records().enumerate() {
        let record = result.with_context(|| {
            format!("parse error on row {} of {}", row_num + 2, path.display())
        })?;

        let fund_name = normalise(record.get(name_col).unwrap_or(""));
        if fund_name.is_empty() {
            continue;
        }

        let value = match parse_dollars(record.get(value_col).unwrap_or("")) {
            Ok(v) if v > 0.0 => v,
            _ => continue,
        };

        holdings.push(RawHolding {
            account_name: account_name.to_string(),
            fund_name,
            value,
        });
    }

    if holdings.is_empty() {
        bail!(
            "No holdings found in Alight CSV '{}'. \
             Download the latest quarterly statement from the SSIP portal.",
            path.display()
        );
    }

    Ok(holdings)
}

// ── Column finder ─────────────────────────────────────────────────────────────

/// Find the index of a column by name (case-insensitive, whitespace-normalised).
fn find_col(headers: &csv::StringRecord, name: &str) -> Option<usize> {
    let target = normalise(name).to_lowercase();
    headers.iter().position(|h| normalise(h).to_lowercase() == target)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn write_temp(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    // ── Vanguard ──────────────────────────────────────────────────────────────

    #[test]
    fn vanguard_parses_by_symbol() {
        // Real Vanguard column names: Investment Name (not Description), no Account Name col
        let csv = "\
Account Number,Investment Name,Symbol,Shares,Share Price,Total Value,
12345,VANGUARD TOTAL STOCK MARKET INDEX ADMIRAL CL,VTSAX,10,100.00,1000.00,
12345,VANGUARD TOTAL INTL STOCK INDEX ADMIRAL CL,VTIAX,5,50.00,250.00,
";
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Vanguard, "Vanguard Roth").unwrap();
        assert_eq!(holdings.len(), 2);
        assert_eq!(holdings[0].fund_name, "VTSAX");
        assert_eq!(holdings[0].value, 1000.0);
        assert_eq!(holdings[1].fund_name, "VTIAX");
        assert_eq!(holdings[1].value, 250.0);
    }

    #[test]
    fn vanguard_strips_dollar_and_commas() {
        let csv = "\
Account Number,Investment Name,Symbol,Shares,Share Price,Total Value,
12345,VANGUARD TOTAL STOCK,VTSAX,10,$234.56,\"$12,345.67\",
";
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Vanguard, "V").unwrap();
        assert_eq!(holdings[0].value, 12345.67);
    }

    #[test]
    fn vanguard_skips_zero_balance() {
        let csv = "\
Account Number,Investment Name,Symbol,Shares,Share Price,Total Value,
12345,VANGUARD TOTAL BOND,VBTLX,0,10.00,0.00,
12345,VANGUARD TOTAL STOCK,VTSAX,5,100.00,500.00,
";
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Vanguard, "V").unwrap();
        assert_eq!(holdings.len(), 1);
        assert_eq!(holdings[0].fund_name, "VTSAX");
    }

    #[test]
    fn vanguard_ignores_transaction_section() {
        // Vanguard exports positions AND transaction history in the same file,
        // separated by blank rows + a new header. Transaction rows have text in
        // the Total Value column position, so they're silently skipped.
        let csv = "\
Account Number,Investment Name,Symbol,Shares,Share Price,Total Value,
12345,VANGUARD TOTAL STOCK,VTSAX,5,100.00,500.00,

Account Number,Trade Date,Settlement Date,Transaction Type,Transaction Description,Investment Name,Symbol,Shares,Share Price,Principal Amount,Commissions and Fees,Net Amount,Accrued Interest,Account Type,
12345,2026-02-02,2026-02-02,Reinvestment,Dividend Reinvestment,VANGUARD TOTAL STOCK,VTSAX,1.0,100.00,-100.00,0.0,-100.00,0.0,CASH,
";
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Vanguard, "V").unwrap();
        assert_eq!(holdings.len(), 1);
        assert_eq!(holdings[0].fund_name, "VTSAX");
        assert_eq!(holdings[0].value, 500.0);
    }

    // ── Empower ───────────────────────────────────────────────────────────────

    #[test]
    fn empower_parses_generated_csv() {
        let csv = "\
Fund Name,Ending Balance
Fidelity 500 Index,5000.00
";
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Empower, "Empower 401k").unwrap();
        assert_eq!(holdings.len(), 1);
        assert_eq!(holdings[0].fund_name, "Fidelity 500 Index");
        assert_eq!(holdings[0].value, 5000.00);
        assert_eq!(holdings[0].account_name, "Empower 401k");
    }

    // ── Alight ────────────────────────────────────────────────────────────────

    #[test]
    fn alight_parses_ssip_csv() {
        let csv = r#""Plan","Category","Asset Class","Fund Name","Current Mix","Future Investments","Date Range","Opening Balance","Gains/Losses","Other Activity","Closing Balance","Units","Fund Price","Fund Return"
"SSIP","Plan Total","Tier 2:  Passive Stock Funds","Vanguard U.S. Large Cap Index Fund","8.0%","0.0%","January 1, 2026 - February 26, 2026","$9,800.00","$200.00","$0.00","$10,000.00","25.000000","$400.000000","2.00%"
"SSIP","Plan Total","Tier 2:  Passive Bond Fund","BlackRock Bond Index Fund","0.0%","0.0%","January 1, 2026 - February 26, 2026","$4,900.00","$100.00","$0.00","$5,000.00","50.000000","$100.000000","2.00%"
"#;
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Alight, "Alight Ford SSIP").unwrap();
        assert_eq!(holdings.len(), 2);
        assert_eq!(holdings[0].fund_name, "Vanguard U.S. Large Cap Index Fund");
        assert!((holdings[0].value - 10000.00).abs() < 0.01);
        assert_eq!(holdings[1].fund_name, "BlackRock Bond Index Fund");
        assert!((holdings[1].value - 5000.00).abs() < 0.01);
    }

    #[test]
    fn alight_skips_zero_balance() {
        let csv = r#""Plan","Category","Asset Class","Fund Name","Current Mix","Future Investments","Date Range","Opening Balance","Gains/Losses","Other Activity","Closing Balance","Units","Fund Price","Fund Return"
"SSIP","Plan Total","Tier 2","Some Fund","0.0%","0.0%","Jan 2026","$0.00","$0.00","$0.00","$0.00","0","$10.00","0.00%"
"SSIP","Plan Total","Tier 2","Active Fund","10.0%","0.0%","Jan 2026","$1000.00","$50.00","$0.00","$1050.00","100","$10.50","5.00%"
"#;
        let f = write_temp(csv);
        let holdings = parse_csv(f.path(), BrokerageFormat::Alight, "Alight").unwrap();
        assert_eq!(holdings.len(), 1);
        assert_eq!(holdings[0].fund_name, "Active Fund");
    }

    // ── normalise ─────────────────────────────────────────────────────────────

    #[test]
    fn normalise_collapses_spaces() {
        assert_eq!(normalise("  Fidelity   500  Index  "), "Fidelity 500 Index");
    }
}
